export const INGREDIENTS = [
  {
    slug: "ui",
    name: "shadcn/ui",
    repo: "shadcn-ui/ui",
    github: "https://github.com/shadcn-ui/ui",
    role: "Plating",
    station: "Front of house",
    category: "interface",
    flavor: "Accessible components you own — copy, season, serve.",
    summary:
      "Beautifully designed components built with Radix UI and Tailwind CSS. Not a package you install blindly: a set of recipes you keep in the kitchen.",
    uses: ["Button systems", "Forms", "Dialogs", "Data tables"],
    pairsWith: ["lucide", "next.js", "create-t3-app", "awesome-tailwindcss"],
    accent: "#d85a1a",
  },
  {
    slug: "lucide",
    name: "Lucide",
    repo: "lucide-icons/lucide",
    github: "https://github.com/lucide-icons/lucide",
    role: "Garnish",
    station: "Finishing",
    category: "interface",
    flavor: "A consistent icon language — the salt on every plate.",
    summary:
      "Beautiful, consistent icons. A community fork of Feather, now the default garnish for serious React interfaces.",
    uses: ["Navigation", "Empty states", "Buttons", "Status"],
    pairsWith: ["ui", "react", "next.js"],
    accent: "#e7c27d",
  },
  {
    slug: "create-t3-app",
    name: "T3 Stack",
    repo: "t3-oss/create-t3-app",
    github: "https://github.com/t3-oss/create-t3-app",
    role: "Mise en place",
    station: "Prep",
    category: "scaffold",
    flavor: "The fastest way to get a typesafe Next.js kitchen running.",
    summary:
      "A full-stack, typesafe starter: Next.js, TypeScript, tRPC, Prisma, Tailwind. Opinionated prep so you can cook, not assemble cupboards.",
    uses: ["Scaffolds", "Type-safe APIs", "Auth starters"],
    pairsWith: ["next.js", "ui", "nodebestpractices"],
    accent: "#2f6f62",
  },
  {
    slug: "directus",
    name: "Directus",
    repo: "directus/directus",
    github: "https://github.com/directus/directus",
    role: "Pantry",
    station: "Stores",
    category: "data",
    flavor: "Turn any SQL database into an API and an admin dining room.",
    summary:
      "The modern data platform that wraps SQL in a clean API and a humane admin UI. Your ingredients, inventoried.",
    uses: ["Headless CMS", "Admin UI", "REST/GraphQL"],
    pairsWith: ["next.js", "nuxt", "jsdelivr"],
    accent: "#6648ff",
  },
  {
    slug: "freeCodeCamp",
    name: "freeCodeCamp",
    repo: "freeCodeCamp/freeCodeCamp",
    github: "https://github.com/freeCodeCamp/freeCodeCamp",
    role: "Apprenticeship",
    station: "Academy",
    category: "learn",
    flavor: "Learn to cook for free — then feed people.",
    summary:
      "A nonprofit curriculum for people who want to build for the web. The long apprenticeship behind every confident plate.",
    uses: ["Curriculum", "Certifications", "Practice"],
    pairsWith: ["javascript-algorithms", "30-seconds-of-code", "css-protips"],
    accent: "#0a0a23",
  },
  {
    slug: "30-seconds-of-code",
    name: "30-seconds-of-code",
    repo: "30-seconds/30-seconds-of-code",
    github: "https://github.com/30-seconds/30-seconds-of-code",
    role: "Knife work",
    station: "Prep",
    category: "learn",
    flavor: "Short, sharp JavaScript cuts. No wasted motion.",
    summary:
      "Bite-size snippets for JavaScript, CSS, React and more. The brunoise of a working developer's day.",
    uses: ["Snippets", "Cheatsheets", "Interviews"],
    pairsWith: ["javascript-algorithms", "css-protips", "react"],
    accent: "#3b82f6",
  },
  {
    slug: "javascript-algorithms",
    name: "javascript-algorithms",
    repo: "trekhleb/javascript-algorithms",
    github: "https://github.com/trekhleb/javascript-algorithms",
    role: "Technique",
    station: "Academy",
    category: "learn",
    flavor: "Algorithms and data structures, explained in JS.",
    summary:
      "Classic computer science, plated in JavaScript: graphs, sorts, searches, dynamic programming — with notes on the side.",
    uses: ["Interviews", "Foundations", "Problem solving"],
    pairsWith: ["30-seconds-of-code", "freeCodeCamp", "nodebestpractices"],
    accent: "#f5c518",
  },
  {
    slug: "react",
    name: "React",
    repo: "facebook/react",
    github: "https://github.com/facebook/react",
    role: "Stock",
    station: "Hot line",
    category: "framework",
    flavor: "The library that made interfaces compositional.",
    summary:
      "The library for web and native user interfaces. Components, hooks, concurrent rendering — the stock every modern kitchen reduces from.",
    uses: ["UI runtime", "Design systems", "Native"],
    pairsWith: ["next.js", "ui", "storybook", "lucide"],
    accent: "#58c4dc",
  },
  {
    slug: "vue",
    name: "Vue",
    repo: "vuejs/vue",
    github: "https://github.com/vuejs/vue",
    role: "Stock",
    station: "Hot line",
    category: "framework",
    flavor: "The progressive framework — approachable, then deep.",
    summary:
      "A progressive JavaScript framework that scales from a sprinkle of interactivity to a full application, without shouting.",
    uses: ["SPAs", "Progressive enhancement", "Design systems"],
    pairsWith: ["nuxt", "awesome-vue", "storybook"],
    accent: "#42b883",
  },
  {
    slug: "angular",
    name: "Angular",
    repo: "angular/angular",
    github: "https://github.com/angular/angular",
    role: "Banquet",
    station: "Hot line",
    category: "framework",
    flavor: "One framework for mobile and desktop — batteries included.",
    summary:
      "A batteries-included platform for ambitious applications: DI, routing, forms, and a compiler that takes craft seriously.",
    uses: ["Enterprise apps", "Design systems", "Mobile & desktop"],
    pairsWith: ["storybook", "nodebestpractices", "jsdelivr"],
    accent: "#dd0031",
  },
  {
    slug: "next.js",
    name: "Next.js",
    repo: "vercel/next.js",
    github: "https://github.com/vercel/next.js",
    role: "Dining room",
    station: "Pass",
    category: "framework",
    flavor: "React, produced. Routing, data, and shipping in one house.",
    summary:
      "The React framework for production. App Router, server components, and a path from prototype to the pass.",
    uses: ["Apps", "Marketing", "Full-stack"],
    pairsWith: ["react", "ui", "create-t3-app", "directus"],
    accent: "#fafafa",
  },
  {
    slug: "nuxt",
    name: "Nuxt",
    repo: "nuxt/nuxt",
    github: "https://github.com/nuxt/nuxt",
    role: "Dining room",
    station: "Pass",
    category: "framework",
    flavor: "The intuitive Vue framework — file-based and server-ready.",
    summary:
      "Nuxt gives Vue a production kitchen: file-based routing, server routes, and conventions that stay out of the way.",
    uses: ["Vue apps", "SSR", "Content sites"],
    pairsWith: ["vue", "awesome-vue", "directus"],
    accent: "#00dc82",
  },
  {
    slug: "awesome-react",
    name: "awesome-react",
    repo: "enaqx/awesome-react",
    github: "https://github.com/enaqx/awesome-react",
    role: "Menu notes",
    station: "Library",
    category: "list",
    flavor: "A curated list of React resources — the annotated menu.",
    summary:
      "A living index of React tools, articles, and components. When you need a specialist, this is the contacts book.",
    uses: ["Discovery", "Research", "Tooling"],
    pairsWith: ["react", "storybook", "ui"],
    accent: "#61dafb",
  },
  {
    slug: "awesome-vue",
    name: "awesome-vue",
    repo: "vuejs/awesome-vue",
    github: "https://github.com/vuejs/awesome-vue",
    role: "Menu notes",
    station: "Library",
    category: "list",
    flavor: "Curated resources for Vue.js cooks.",
    summary:
      "Components, libraries, tutorials and talks — the Vue world's annotated menu, kept by the community.",
    uses: ["Discovery", "Libraries", "Learning"],
    pairsWith: ["vue", "nuxt"],
    accent: "#42b883",
  },
  {
    slug: "nodebestpractices",
    name: "nodebestpractices",
    repo: "goldbergyoni/nodebestpractices",
    github: "https://github.com/goldbergyoni/nodebestpractices",
    role: "Hygiene",
    station: "Pass",
    category: "learn",
    flavor: "How a Node kitchen stays clean under pressure.",
    summary:
      "The most voted Node.js best-practices list on GitHub: structure, errors, security, testing — the health inspection.",
    uses: ["Architecture", "Errors", "Security"],
    pairsWith: ["create-t3-app", "directus", "javascript-algorithms"],
    accent: "#68a063",
  },
  {
    slug: "storybook",
    name: "Storybook",
    repo: "storybookjs/storybook",
    github: "https://github.com/storybookjs/storybook",
    role: "Tasting menu",
    station: "Lab",
    category: "tooling",
    flavor: "Isolate a component, taste it, send it to the line.",
    summary:
      "A workshop for UI components. Build, test and document in isolation before anything reaches the dining room.",
    uses: ["Component labs", "Docs", "Visual tests"],
    pairsWith: ["react", "vue", "angular", "ui"],
    accent: "#ff4785",
  },
  {
    slug: "css-protips",
    name: "css-protips",
    repo: "AllThingsSmitty/css-protips",
    github: "https://github.com/AllThingsSmitty/css-protips",
    role: "Seasoning",
    station: "Prep",
    category: "learn",
    flavor: "Small CSS moves that change the whole dish.",
    summary:
      "A collection of tips to take CSS from competent to professional: selectors, resets, rhythm, and craft.",
    uses: ["Layout", "Resets", "Specificity"],
    pairsWith: ["awesome-tailwindcss", "ui", "30-seconds-of-code"],
    accent: "#2965f1",
  },
  {
    slug: "awesome-tailwindcss",
    name: "awesome-tailwindcss",
    repo: "aniftyco/awesome-tailwindcss",
    github: "https://github.com/aniftyco/awesome-tailwindcss",
    role: "Spice rack",
    station: "Library",
    category: "list",
    flavor: "Plugins, UI kits, and ideas for a utility-first kitchen.",
    summary:
      "A curated shelf of Tailwind resources — the spice rack next to shadcn/ui and whatever you're plating tonight.",
    uses: ["Plugins", "UI kits", "Inspiration"],
    pairsWith: ["ui", "next.js", "css-protips"],
    accent: "#38bdf8",
  },
  {
    slug: "jsdelivr",
    name: "jsDelivr",
    repo: "md8-habibullah/jsdelivr",
    github: "https://github.com/md8-habibullah/jsdelivr",
    role: "Delivery",
    station: "Service",
    category: "infra",
    flavor: "A free CDN for open source, npm, GitHub, and more.",
    summary:
      "The courier. Serve npm packages, GitHub files and WordPress plugins from a global edge so the plate arrives hot.",
    uses: ["CDN", "npm", "GitHub files"],
    pairsWith: ["react", "vue", "lucide", "directus"],
    accent: "#e64a19",
  },
];

export const RECIPES = [
  {
    slug: "the-house-plate",
    name: "The House Plate",
    course: "Signature",
    time: "A weekend",
    summary:
      "React, Next.js, shadcn/ui and Lucide — the house combination. Typesafe from the T3 starter, hygienic Node habits on the pass.",
    ingredients: ["react", "next.js", "ui", "lucide", "create-t3-app", "nodebestpractices"],
    method: [
      "Scaffold with create-t3-app so TypeScript, Tailwind and routing are already in place.",
      "Bring in shadcn/ui components as owned source — not a black-box package.",
      "Garnish every interactive state with Lucide, keeping a single icon language.",
      "Serve through Next.js App Router. Keep mutations on the server.",
      "Read nodebestpractices before you invent error handling. You won't.",
    ],
    yield: "A production Next.js product with a design system you actually own.",
  },
  {
    slug: "vue-tasting",
    name: "Vue Tasting Menu",
    course: "Alternative",
    time: "A long afternoon",
    summary:
      "Vue and Nuxt, with Storybook as the tasting counter and awesome-vue as the annotated menu.",
    ingredients: ["vue", "nuxt", "awesome-vue", "storybook", "directus"],
    method: [
      "Start a Nuxt app — file-based routing is the mise.",
      "Pull content or product data through Directus so editors stay out of the repo.",
      "Isolate new components in Storybook before they reach a page.",
      "Use awesome-vue when you need a specialist library instead of writing one.",
    ],
    yield: "A Vue product with a content pantry and a component lab.",
  },
  {
    slug: "apprentice-board",
    name: "Apprentice Board",
    course: "Study",
    time: "Ongoing",
    summary:
      "freeCodeCamp for the long apprenticeship, 30-seconds for daily knife work, algorithms for technique, CSS protips for seasoning.",
    ingredients: [
      "freeCodeCamp",
      "30-seconds-of-code",
      "javascript-algorithms",
      "css-protips",
      "nodebestpractices",
    ],
    method: [
      "Follow a freeCodeCamp certification as the spine of the week.",
      "Do one 30-seconds snippet every morning — muscle memory.",
      "When a snippet isn't enough, open javascript-algorithms and learn why.",
      "Season layouts with a CSS protip instead of another dependency.",
      "Before you ship a Node service, walk the hygiene list.",
    ],
    yield: "A sharper cook. Not a new framework.",
  },
  {
    slug: "banquet-service",
    name: "Banquet Service",
    course: "Enterprise",
    time: "A quarter",
    summary:
      "Angular for the banquet hall, Storybook for tasting, Directus for inventory, jsDelivr for delivery.",
    ingredients: ["angular", "storybook", "directus", "jsdelivr", "nodebestpractices"],
    method: [
      "Use Angular when the table is large and the courses are many.",
      "Document every shared component in Storybook — banquet service has no mystery garnishes.",
      "Directus as the source of truth for editorial and operational data.",
      "Ship static assets through jsDelivr when you need a courier, not a kitchen.",
    ],
    yield: "An enterprise frontend with a clear inventory and a tested component line.",
  },
];
